Repository nobl9/nobl9-go, pull requests merged in 2024-07, with the labels that each got.

#475 feat: Add Alert Method types
  .github/workflows/checks.yml
  manifest/v1alpha/agent/agent.go
  manifest/v1alpha/alert_methods.go
  manifest/v1alpha/alert_methods_enum.go
  manifest/v1alpha/alertmethod/alert_method.go
  manifest/v1alpha/alertmethod/alert_method_test.go
Labels: enhancement, go, minor

#476 chore: Correct Alert Method type names
  manifest/v1alpha/alert_methods.go
  manifest/v1alpha/alert_methods_enum.go
  manifest/v1alpha/alertmethod/alert_method.go
Labels: chore, patch, go

#482 chore: Switch go-yaml library to Nobl9 fork
  .golangci.yml
  go.mod
  go.sum
  internal/cmd/docgen/main.go
  internal/manifest/v1alphatest/labels_validation.go
  internal/manifest/v1alphatest/metadata_annotations_validation.go
  internal/validation/example_test.go
  manifest/v1alpha/dataexport/data_export.go
  manifest/v1alpha/parser/parser.go
  sdk/decode.go
  sdk/decode_test.go
  sdk/encode.go
Labels: chore, patch, go

#481 chore: Add Alert Method e2e tests
  manifest/object.go
  tests/examples_test.go
  tests/helpers_test.go
  tests/v1alpha_alertmethod_test.go
  tests/v1alpha_project_test.go
  tests/v1alpha_service_test.go
Labels: chore, patch, go

#458 feat: PC-13045 Good total single query experimental support
  cspell.yaml
  manifest/v1alpha/slo/metrics.go
  manifest/v1alpha/slo/metrics_bigquery_test.go
  manifest/v1alpha/slo/metrics_splunk.go
  manifest/v1alpha/slo/metrics_splunk_test.go
  manifest/v1alpha/slo/metrics_test.go
  manifest/v1alpha/slo/metrics_validation.go
  manifest/v1alpha/slo/metrics_validation_test.go
  manifest/v1alpha/slo/validation_test.go
Labels: enhancement, go, minor

#490 chore: Add v1alpha Agent and Direct end-to-end tests
  internal/manifest/objects_test.go
  internal/manifest/v1alpha/examples/agent.go
  internal/manifest/v1alpha/examples/alert_method.go
  internal/manifest/v1alpha/examples/alert_method_test.go
  internal/manifest/v1alpha/examples/direct.go
  manifest/v1alpha/agent/examples/amazon-prometheus.yaml
  manifest/v1alpha/agent/examples/app-dynamics.yaml
  manifest/v1alpha/agent/examples/azure-monitor.yaml
  manifest/v1alpha/agent/examples/azure-prometheus.yaml
  manifest/v1alpha/agent/examples/big-query.yaml
  manifest/v1alpha/agent/examples/cloud-watch.yaml
  manifest/v1alpha/agent/examples/datadog.yaml
  manifest/v1alpha/agent/examples/dynatrace.yaml
  manifest/v1alpha/agent/examples/elasticsearch.yaml
  manifest/v1alpha/agent/examples/generic.yaml
  manifest/v1alpha/agent/examples/google-cloud-monitoring.yaml
  manifest/v1alpha/agent/examples/grafana-loki.yaml
  manifest/v1alpha/agent/examples/graphite.yaml
  manifest/v1alpha/agent/examples/honeycomb.yaml
  manifest/v1alpha/agent/examples/influx-d-b.yaml
  manifest/v1alpha/agent/examples/instana.yaml
  manifest/v1alpha/agent/examples/lightstep.yaml
  manifest/v1alpha/agent/examples/logic-monitor.yaml
  manifest/v1alpha/agent/examples/new-relic.yaml
  manifest/v1alpha/agent/examples/open-t-s-d-b.yaml
  manifest/v1alpha/agent/examples/pingdom.yaml
  manifest/v1alpha/agent/examples/prometheus.yaml
  manifest/v1alpha/agent/examples/redshift.yaml
  manifest/v1alpha/agent/examples/splunk-observability.yaml
  manifest/v1alpha/agent/examples/splunk.yaml
  manifest/v1alpha/agent/examples/sumo-logic.yaml
  manifest/v1alpha/agent/examples/thousand-eyes.yaml
  manifest/v1alpha/data_sources.go
  manifest/v1alpha/direct/examples/app-dynamics.yaml
  manifest/v1alpha/direct/examples/azure-monitor.yaml
  manifest/v1alpha/direct/examples/big-query.yaml
  manifest/v1alpha/direct/examples/cloud-watch.yaml
  manifest/v1alpha/direct/examples/datadog.yaml
  manifest/v1alpha/direct/examples/dynatrace.yaml
  manifest/v1alpha/direct/examples/google-cloud-monitoring.yaml
  manifest/v1alpha/direct/examples/honeycomb.yaml
  manifest/v1alpha/direct/examples/influx-d-b.yaml
  manifest/v1alpha/direct/examples/instana.yaml
  manifest/v1alpha/direct/examples/lightstep.yaml
  manifest/v1alpha/direct/examples/logic-monitor.yaml
  manifest/v1alpha/direct/examples/new-relic.yaml
  manifest/v1alpha/direct/examples/pingdom.yaml
  manifest/v1alpha/direct/examples/redshift.yaml
  manifest/v1alpha/direct/examples/splunk-observability.yaml
  manifest/v1alpha/direct/examples/splunk.yaml
  manifest/v1alpha/direct/examples/sumo-logic.yaml
  manifest/v1alpha/direct/examples/thousand-eyes.yaml
  tests/examples_test.go
  tests/v1alpha_agent_test.go
  tests/v1alpha_alertmethod_test.go
  tests/v1alpha_alertpolicy_test.go
  tests/v1alpha_direct_test.go
  tests/v1alpha_project_test.go
  tests/v1alpha_service_test.go
Labels: chore, patch, go

#494 chore: Add SLO end-to-end tests
  Makefile
  cspell.yaml
  go.mod
  go.sum
  internal/cmd/docgen/object_doc.go
  internal/manifest/v1alpha/examples/agent.go
  internal/manifest/v1alpha/examples/direct.go
  internal/manifest/v1alpha/examples/slo_variants.go
  manifest/v1alpha/agent/examples/cloud-watch.yaml
  manifest/v1alpha/agent/examples/google-cloud-monitoring.yaml
  manifest/v1alpha/direct/examples/google-cloud-monitoring.yaml
  manifest/v1alpha/slo/examples/amazon-prometheus.yaml
  manifest/v1alpha/slo/examples/app-dynamics.yaml
  manifest/v1alpha/slo/examples/azure-monitor.yaml
  manifest/v1alpha/slo/examples/azure-prometheus.yaml
  manifest/v1alpha/slo/examples/big-query.yaml
  manifest/v1alpha/slo/examples/cloud-watch.yaml
  manifest/v1alpha/slo/examples/datadog.yaml
  manifest/v1alpha/slo/examples/dynatrace.yaml
  manifest/v1alpha/slo/examples/elasticsearch.yaml
  manifest/v1alpha/slo/examples/generic.yaml
  manifest/v1alpha/slo/examples/google-cloud-monitoring.yaml
  manifest/v1alpha/slo/examples/grafana-loki.yaml
  manifest/v1alpha/slo/examples/graphite.yaml
  manifest/v1alpha/slo/examples/honeycomb.yaml
  manifest/v1alpha/slo/examples/influx-d-b.yaml
  manifest/v1alpha/slo/examples/instana.yaml
  manifest/v1alpha/slo/examples/lightstep.yaml
  manifest/v1alpha/slo/examples/logic-monitor.yaml
  manifest/v1alpha/slo/examples/new-relic.yaml
  manifest/v1alpha/slo/examples/open-t-s-d-b.yaml
  manifest/v1alpha/slo/examples/pingdom.yaml
  manifest/v1alpha/slo/examples/prometheus.yaml
  manifest/v1alpha/slo/examples/redshift.yaml
  manifest/v1alpha/slo/examples/splunk-observability.yaml
  manifest/v1alpha/slo/examples/splunk.yaml
  manifest/v1alpha/slo/examples/sumo-logic.yaml
  manifest/v1alpha/slo/examples/thousand-eyes.yaml
  sdk/http.go
  tests/examples_test.go
  tests/helpers_test.go
  tests/main_test.go
  tests/v1alpha_agent_test.go
  tests/v1alpha_alertmethod_test.go
  tests/v1alpha_alertpolicy_test.go
  tests/v1alpha_direct_test.go
  tests/v1alpha_project_test.go
  tests/v1alpha_rolebinding_test.go
  tests/v1alpha_service_test.go
  tests/v1alpha_slo_test.go
Labels: chore, patch, go

#498 chore: Allow sequential apply/delete execution for end-to-end tests
  .github/workflows/e2e-tests-dispatch.yml
  .github/workflows/e2e-tests.yml
  tests/helpers_test.go
  tests/v1alpha_agent_test.go
  tests/v1alpha_slo_test.go
Labels: chore, patch, go

#499 chore: Add Alert Silence end-to-end tests
  tests/v1alpha_alertsilence_test.go
Labels: chore, patch, go

#500 chore: Add Data Export end-to-end tests
  tests/v1alpha_dataexport_test.go
Labels: chore, patch, go

#501 chore: Add Annotations end-to-end tests
  tests/helpers_test.go
  tests/v1alpha_annotation_test.go
Labels: chore, patch, go

#449 feat: PC-13028 Support Azure Monitor managed service for Prometheus in Direct
  internal/manifest/v1alpha/examples/direct.go
  internal/validation/string.go
  manifest/v1alpha/data_sources.go
  manifest/v1alpha/direct/direct.go
  manifest/v1alpha/direct/validation.go
  manifest/v1alpha/direct/validation_test.go
Labels: enhancement, go, minor

#504 fix: Fix tests for Azure Prometheus Direct [PC-13028]
  internal/manifest/v1alpha/examples/direct.go
  tests/v1alpha_direct_test.go
Labels: bug, patch, go

#507 chore: gitsync updates
  .github/renovate.json5
  .github/scripts/release-notes.sh
  .golangci.yml
Labels: chore, patch
