Repository nobl9/nobl9-go, pull requests merged in 2024-08, with the labels that each got.

#509 chore: Update developer docs and examples
  docs/DEVELOPMENT.md
  internal/cmd/docgen/README.md
  internal/cmd/examplegen/README.md
  internal/manifest/v1alpha/examples/doc.go
  internal/manifest/v1alpha/examples/example_test.go
  manifest/kind.go
Labels: chore, patch, go

#495 feat: PC-13263 Add Report kind
  cspell.yaml
  docs/mock_example/mocks/objects_v1.go
  internal/cmd/docgen/objects.go
  internal/cmd/examplegen/main.go
  internal/manifest/v1alpha/examples/report.go
  manifest/kind.go
  manifest/kind_enum.go
  manifest/v1alpha/parser/parser.go
  manifest/v1alpha/report/doc.go
  manifest/v1alpha/report/example_test.go
  manifest/v1alpha/report/examples.yaml
  manifest/v1alpha/report/report.go
  manifest/v1alpha/report/report_object.go
  manifest/v1alpha/report/row_group_by.go
  manifest/v1alpha/report/row_group_by_enum.go
  manifest/v1alpha/report/slo_history.go
  manifest/v1alpha/report/snapshot_point.go
  manifest/v1alpha/report/snapshot_point_enum.go
  manifest/v1alpha/report/system_health_review.go
  manifest/v1alpha/report/validation.go
  manifest/v1alpha/report/validation_slo_history.go
  manifest/v1alpha/report/validation_system_health_review.go
  manifest/v1alpha/report/validation_test.go
  sdk/endpoints/objects/v1/endpoints_interface.go
  sdk/endpoints/objects/v1/endpoints_v1alpha.go
  sdk/endpoints/objects/v1/request.go
Labels: enhancement, go, minor

#514 fix: Removing redundant validation in LogicMonitor [PC-13783]
  manifest/v1alpha/direct/validation.go
  manifest/v1alpha/direct/validation_test.go
Labels: bug, patch, go

#513 chore: Adjust release doc
  docs/RELEASE.md
Labels: chore, patch

#518 chore: PC-13881 Fix comment about composites 2.0 being unavailable
  manifest/v1alpha/slo/slo.go
Labels: chore, patch, go

#516 chore: PC-13744 Composite SLOs in examples and SDK e2e tests
  Makefile
  internal/manifest/v1alpha/examples/slo.go
  internal/manifest/v1alpha/examples/slo_composite.go
  internal/manifest/v1alpha/examples/slo_variants.go
  internal/manifest/v1alpha/examples/validation_test.go
  manifest/v1alpha/direct/examples/azure-prometheus.yaml
  manifest/v1alpha/slo/examples/composite-slo.yaml
  scripts/check-generate.sh
  sdk/config_activity.png
  tests/v1alpha_alertsilence_test.go
  tests/v1alpha_annotation_test.go
  tests/v1alpha_slo_test.go
Labels: chore, patch, go

#520 fix: PC-13744 Removed anomaly config from composite e2e test
  internal/manifest/v1alpha/examples/slo_composite.go
  manifest/v1alpha/slo/examples/composite-slo.yaml
Labels: bug, patch, go

#523 chore: Update DEVELOPMENT.md
  docs/DEVELOPMENT.md
Labels: chore, patch

#526 feat: PC-13831 unique SLOs validation and test
  manifest/v1alpha/budgetadjustment/validation.go
  manifest/v1alpha/budgetadjustment/validation_test.go
Labels: enhancement, go, minor, passed-testing
