Repository nobl9/nobl9-go, pull requests merged in 2024-12, with the labels that each got.

#595 chore: Remove Status from kind AlertMethod
  manifest/v1alpha/alertmethod/alert_method.go
Labels: breaking-change, chore, patch, go

#598 feat: PC-14959 Extend kind SLO with QueryValidationStatus
  cspell.yaml
  manifest/v1alpha/slo/metrics.go
  manifest/v1alpha/slo/metrics_test.go
  manifest/v1alpha/slo/slo.go
Labels: enhancement, go, minor

#603 chore: Update golangci linter config
  .golangci.yml
  Makefile
  tests/helpers_test.go
  tests/main_test.go
  tests/v1alpha_alertmethod_test.go
  tests/v1alpha_annotation_test.go
  tests/v1alpha_direct_test.go
  tests/v1alpha_slo_test.go
Labels: chore, patch, go

#549 feat: PC-13893 Deprecate usage of objective's value field for Composite SLOs
  internal/manifest/v1alpha/examples/slo_composite.go
  manifest/v1alpha/slo/examples/composite-slo.yaml
  manifest/v1alpha/slo/slo.go
  sdk/test_data/reader/expected/composite_v2_slo.tpl.json
Labels: enhancement, go, minor

#606 fix: E2E tests are failing for composite SLOs
  tests/v1alpha_slo_test.go
Labels: bug, patch, go

#609 chore: PC-15033 Remove triggeredBySLOCreation and Edit
  internal/manifest/v1alpha/examples/agent.go
  internal/manifest/v1alpha/examples/direct.go
  manifest/v1alpha/agent/examples/amazon-prometheus.yaml
  manifest/v1alpha/agent/examples/app-dynamics.yaml
  manifest/v1alpha/agent/examples/azure-monitor.yaml
  manifest/v1alpha/agent/examples/azure-prometheus.yaml
  manifest/v1alpha/agent/examples/cloud-watch.yaml
  manifest/v1alpha/agent/examples/datadog.yaml
  manifest/v1alpha/agent/examples/dynatrace.yaml
  manifest/v1alpha/agent/examples/elasticsearch.yaml
  manifest/v1alpha/agent/examples/google-cloud-monitoring.yaml
  manifest/v1alpha/agent/examples/graphite.yaml
  manifest/v1alpha/agent/examples/honeycomb.yaml
  manifest/v1alpha/agent/examples/lightstep.yaml
  manifest/v1alpha/agent/examples/logic-monitor.yaml
  manifest/v1alpha/agent/examples/new-relic.yaml
  manifest/v1alpha/agent/examples/prometheus.yaml
  manifest/v1alpha/agent/examples/splunk.yaml
  manifest/v1alpha/agent/validation.go
  manifest/v1alpha/agent/validation_test.go
  manifest/v1alpha/data_sources.go
  manifest/v1alpha/direct/examples/app-dynamics.yaml
  manifest/v1alpha/direct/examples/azure-monitor.yaml
  manifest/v1alpha/direct/examples/azure-prometheus.yaml
  manifest/v1alpha/direct/examples/cloud-watch.yaml
  manifest/v1alpha/direct/examples/datadog.yaml
  manifest/v1alpha/direct/examples/dynatrace.yaml
  manifest/v1alpha/direct/examples/google-cloud-monitoring.yaml
  manifest/v1alpha/direct/examples/honeycomb.yaml
  manifest/v1alpha/direct/examples/lightstep.yaml
  manifest/v1alpha/direct/examples/logic-monitor.yaml
  manifest/v1alpha/direct/examples/new-relic.yaml
  manifest/v1alpha/direct/examples/splunk.yaml
  manifest/v1alpha/direct/validation.go
  manifest/v1alpha/direct/validation_test.go
Labels: chore, patch, go

#611 fix: Fix budget adjustments e2e tests
  tests/v1alpha_budgetadjustment_test.go
Labels: bug, patch, go

#613 fix: Adjust validation for missing metric spec [PC-15176]
  manifest/v1alpha/slo/metrics_validation.go
  manifest/v1alpha/slo/validation.go
  manifest/v1alpha/slo/validation_test.go
Labels: bug, patch, go
