Repository nobl9/nobl9-go, pull requests merged in 2024-10, with the labels that each got.

#531 feat: Expose structured API response errors
  Makefile
  README.md
  cspell.yaml
  docs/CONTRIBUTING.md
  docs/DEVELOPMENT.md
  internal/sdk/response_errors.go
  internal/sdk/response_errors_test.go
  sdk/api_error.tmpl
  sdk/client.go
  sdk/client_errors.go
  sdk/client_errors_test.go
  sdk/client_test.go
  sdk/config.go
  sdk/config_activity.png
  sdk/config_activity.puml
  sdk/endpoints/authdata/v1/endpoints.go
  sdk/endpoints/objects/v1/endpoints.go
  sdk/endpoints/objects/v1/endpoints_v1alpha.go
Labels: enhancement, go, minor

#560 fix: add max query delay validation per data source
  manifest/v1alpha/agent/validation.go
  manifest/v1alpha/agent/validation_test.go
  manifest/v1alpha/data_sources.go
  manifest/v1alpha/direct/validation.go
  manifest/v1alpha/direct/validation_test.go
Labels: bug, patch, go

#543 feat: PC-14184 Add sourceSLO field in replay config file
  manifest/v1alpha/slo/slo.go
  sdk/models/replay.go
  sdk/models/replay_test.go
Labels: enhancement, go, minor, passed-testing

#559 feat: PC-13340 Replay on SLO edit/creation - DataSource setting
  internal/manifest/v1alpha/examples/agent.go
  internal/manifest/v1alpha/examples/direct.go
  manifest/v1alpha/agent/examples/amazon-prometheus.yaml
  manifest/v1alpha/agent/examples/app-dynamics.yaml
  manifest/v1alpha/agent/examples/azure-monitor.yaml
  manifest/v1alpha/agent/examples/azure-prometheus.yaml
  manifest/v1alpha/agent/examples/cloud-watch.yaml
  manifest/v1alpha/agent/examples/datadog.yaml
  manifest/v1alpha/agent/examples/dynatrace.yaml
  manifest/v1alpha/agent/examples/google-cloud-monitoring.yaml
  manifest/v1alpha/agent/examples/graphite.yaml
  manifest/v1alpha/agent/examples/honeycomb.yaml
  manifest/v1alpha/agent/examples/lightstep.yaml
  manifest/v1alpha/agent/examples/logic-monitor.yaml
  manifest/v1alpha/agent/examples/new-relic.yaml
  manifest/v1alpha/agent/examples/prometheus.yaml
  manifest/v1alpha/agent/examples/splunk.yaml
  manifest/v1alpha/agent/validation.go
  manifest/v1alpha/agent/validation_test.go
  manifest/v1alpha/data_sources.go
  manifest/v1alpha/direct/examples/app-dynamics.yaml
  manifest/v1alpha/direct/examples/azure-monitor.yaml
  manifest/v1alpha/direct/examples/azure-prometheus.yaml
  manifest/v1alpha/direct/examples/cloud-watch.yaml
  manifest/v1alpha/direct/examples/datadog.yaml
  manifest/v1alpha/direct/examples/dynatrace.yaml
  manifest/v1alpha/direct/examples/google-cloud-monitoring.yaml
  manifest/v1alpha/direct/examples/honeycomb.yaml
  manifest/v1alpha/direct/examples/lightstep.yaml
  manifest/v1alpha/direct/examples/logic-monitor.yaml
  manifest/v1alpha/direct/examples/new-relic.yaml
  manifest/v1alpha/direct/examples/splunk.yaml
  manifest/v1alpha/direct/validation.go
  manifest/v1alpha/direct/validation_test.go
Labels: enhancement, go, minor, passed-testing

#537 feat: PC-14087 Add SLO Status API to SDK
  cspell.yaml
  sdk/client.go
  sdk/endpoints/slostatusapi/doc.go
  sdk/endpoints/slostatusapi/v1/doc.go
  sdk/endpoints/slostatusapi/v1/endpoints.go
  sdk/endpoints/slostatusapi/v1/endpoints_interface.go
  sdk/endpoints/slostatusapi/v1/query.go
  sdk/endpoints/slostatusapi/v1/request.go
  sdk/endpoints/slostatusapi/v1/response.go
  sdk/endpoints/slostatusapi/v2/doc.go
  sdk/endpoints/slostatusapi/v2/endpoints.go
  sdk/endpoints/slostatusapi/v2/endpoints_interface.go
  sdk/endpoints/slostatusapi/v2/query.go
  sdk/endpoints/slostatusapi/v2/request.go
  sdk/endpoints/slostatusapi/v2/response.go
  sdk/endpoints/slostatusapi/versions.go
  sdk/endpoints/slostatusapi/versions_interface.go
  tests/slostatusapi_test.go
Labels: enhancement, go, minor

#571 fix: PC-14087 Adjust SLO Status API tests
  tests/slostatusapi_test.go
Labels: bug, patch, go

#567 feat: Add standardized API errors
  sdk/api_error.tmpl
  sdk/client_errors.go
  sdk/client_errors_test.go
  sdk/http_error.tmpl
  sdk/http_errors.go
  sdk/http_errors_test.go
Labels: enhancement, breaking-change, go, minor

#570 feat: extend SLO status by most recent process status [PC-14514]
  manifest/v1alpha/slo/slo.go
  sdk/models/replay.go
Labels: enhancement, go, minor

#578 feat: add Duration() to v1alpha.HistoricalRetrievalDuration
  manifest/v1alpha/data_sources.go
  manifest/v1alpha/data_sources_test.go
Labels: enhancement, go, minor

#579 feat: Add APIErrors struct
  sdk/http_errors.go
  sdk/http_errors_test.go
Labels: enhancement, go, minor

#580 chore: Add Error() to APIErrors (string representation of APIErrors)
  sdk/http_error.tmpl
  sdk/http_errors.go
  sdk/http_errors_test.go
Labels: chore, patch, go

#561 chore: PC-14075 Add field
  manifest/v1alpha/slo/slo.go
  manifest/v1alpha/slo/validation.go
Labels: chore, patch, go

#581 feat: allow constant keyword in ServiceNow Obs (Lightstep) UQL queries [PC-14700]
  manifest/v1alpha/slo/metrics_lightstep.go
  manifest/v1alpha/slo/metrics_lightstep_test.go
Labels: enhancement, go, minor, passed-testing
