Repository nobl9/nobl9-go, pull requests merged in 2024-06, with the labels that each got.

#445 fix: composite slo name and displayName validation [PC-12850]
  go.work.sum
  manifest/v1alpha/slo/validation.go
  manifest/v1alpha/slo/validation_composite_test.go
Labels: bug, patch, go

#454 chore: Add end-to-end Project and Service tests
  .github/workflows/e2e-tests-dispatch.yml
  .github/workflows/e2e-tests.yml
  .gitignore
  Makefile
  docs/mock_example/go.mod
  docs/mock_example/go.sum
  go.mod
  go.sum
  go.work
  go.work.sum
  sdk/credentials.go
  tests/helpers_test.go
  tests/main_test.go
  tests/v1alpha_project_test.go
  tests/v1alpha_service_test.go
Labels: chore, patch, go

#456 chore: Add no config file
  .github/workflows/e2e-tests.yml
Labels: chore, patch

#437 feat: PC-13027 PC-13029 Add Azure Monitor managed service for Prometh…
  manifest/v1alpha/agent/agent.go
  manifest/v1alpha/agent/validation.go
  manifest/v1alpha/agent/validation_test.go
  manifest/v1alpha/data_sources.go
  manifest/v1alpha/data_sources_enum.go
  manifest/v1alpha/slo/metrics.go
  manifest/v1alpha/slo/metrics_azure_prometheus.go
  manifest/v1alpha/slo/metrics_azure_prometheus_test.go
  manifest/v1alpha/slo/metrics_logic_monitor_test.go
  manifest/v1alpha/slo/metrics_validation.go
  manifest/v1alpha/slo/validation_test.go
Labels: enhancement, go, minor

#423 feat: PC-12940/PC-12941 Allow to configure budget drop condition type
  manifest/v1alpha/alertpolicy/measurement.go
  manifest/v1alpha/alertpolicy/validation.go
  manifest/v1alpha/alertpolicy/validation_test.go
Labels: enhancement, go, minor

#471 fix: Double quoted JSON handling
  go.mod
  go.sum
  manifest/v1alpha/parser/parser_test.go
  manifest/v1alpha/parser/test_data/cloudwatch_slo.yaml
Labels: bug, patch, go
