Repository nobl9/nobl9-go, pull requests merged in 2024-02, with the labels that each got.

#238 feat: sumologic timeslice validation [PC-7427]
  cspell.yaml
  manifest/v1alpha/slo/metrics_sumo_logic.go
  manifest/v1alpha/slo/metrics_sumo_logic_test.go
  sdk/test_data/client/simple_module/go.mod
  sdk/test_data/client/simple_module/go.sum
Labels: enhancement, go, minor

#264 chore: Interpret git log grep pattern as literal string
  .github/scripts/release-notes.sh
Labels: chore, patch

#265 chore: Remove dependencies section from Release Drafter
  .github/release-drafter.yml
Labels: chore, patch

#261 feat: Add fields to Agent Status showing newest available agent versions [PC-11737]
  manifest/v1alpha/agent/agent.go
Labels: enhancement, go, minor

#269 chore: Fix issue template typos
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: chore, patch

#273 fix: Revert "chore: Update dependency golangci/golangci-lint to v1.56.1 (#…
  Makefile
Labels: bug, patch

#279 chore: Update pr-title.yml
  .github/workflows/pr-title.yml
Labels: chore, patch

#262 feat: PC-11843 budget adjustment kind
  cspell.yaml
  go.mod
  go.sum
  internal/validation/duration.go
  internal/validation/duration_test.go
  internal/validation/error_codes.go
  manifest/kind.go
  manifest/kind_enum.go
  manifest/v1alpha/alertpolicy/validation.go
  manifest/v1alpha/alertpolicy/validation_test.go
  manifest/v1alpha/budgetadjustment/budget_adjustment.go
  manifest/v1alpha/budgetadjustment/budget_adjustment_object.go
  manifest/v1alpha/budgetadjustment/doc.go
  manifest/v1alpha/budgetadjustment/example.yaml
  manifest/v1alpha/budgetadjustment/example_test.go
  manifest/v1alpha/budgetadjustment/validation.go
  manifest/v1alpha/budgetadjustment/validation_test.go
  manifest/v1alpha/parser/parser.go
  manifest/v1alpha/parser/parser_test.go
  sdk/config_activity.png
Labels: enhancement, go, minor, release-notes

#254 feat: PC-11299 Honeycomb query batching enablers - allow setting `attribute` for `COUNT` and `CONCURRENCY` calculation methods
  manifest/v1alpha/slo/metrics_honeycomb.go
  manifest/v1alpha/slo/metrics_honeycomb_test.go
  manifest/v1alpha/slo/metrics_validation.go
  sdk/test_data/client/simple_module/go.mod
  sdk/test_data/client/simple_module/go.sum
Labels: enhancement, go, minor

#257 feat: Switch back to native yaml decoding
  cspell.yaml
  internal/serdeutil/doc.go
  internal/serdeutil/raw_message.go
  manifest/v1alpha/dataexport/data_export.go
  manifest/v1alpha/parser/parser.go
Labels: enhancement, go, minor, release-notes

#291 doc: Document release and development workflows
  .github/pull_request_template.md
  .github/release-drafter.yml
  .github/scripts/release-notes.sh
  .markdownlint.yaml
  Makefile
  docs/DEVELOPMENT.md
  docs/RELEASE.md
  internal/validation/README.md
Labels: documentation

#297 chore: PC-12175 Make honeycomb public in SDK
  manifest/v1alpha/slo/metrics_honeycomb.go
Labels: chore, patch, go

#288 feat: Switch to new major JWT library and new JWK handler
  .github/release-drafter.yml
  cspell.yaml
  go.mod
  go.sum
  internal/testutils/record.go
  sdk/client_authdata_v1_test.go
  sdk/client_objects_v1_test.go
  sdk/client_test.go
  sdk/credentials.go
  sdk/credentials_test.go
  sdk/http.go
  sdk/jwt.go
  sdk/jwt_test.go
Labels: enhancement, go, minor, release-notes
