Repository nobl9/nobl9-go, pull requests merged in 2024-09, with the labels that each got.

#536 chore: export metric spec validation rules
  manifest/v1alpha/slo/metrics_validation.go
  manifest/v1alpha/slo/validation.go
Labels: chore, patch, go

#539 chore: Add explicit generic arguments as workaround for GoLand IDE bug
  manifest/v1alpha/annotation/validation.go
  manifest/v1alpha/budgetadjustment/validation.go
  manifest/v1alpha/data_sources.go
  manifest/v1alpha/direct/validation.go
  manifest/v1alpha/labels.go
  manifest/v1alpha/metadata_annotations.go
  manifest/v1alpha/project/validation.go
  manifest/v1alpha/report/validation.go
  manifest/v1alpha/slo/metrics_amazon_prometheus.go
  manifest/v1alpha/slo/metrics_app_dynamics.go
  manifest/v1alpha/slo/metrics_azure_monitor.go
  manifest/v1alpha/slo/metrics_azure_prometheus.go
  manifest/v1alpha/slo/metrics_bigquery.go
  manifest/v1alpha/slo/metrics_cloudwatch.go
  manifest/v1alpha/slo/metrics_datadog.go
  manifest/v1alpha/slo/metrics_dynatrace.go
  manifest/v1alpha/slo/metrics_elasticsearch.go
  manifest/v1alpha/slo/metrics_gcm.go
  manifest/v1alpha/slo/metrics_generic.go
  manifest/v1alpha/slo/metrics_grafana_loki.go
  manifest/v1alpha/slo/metrics_graphite.go
  manifest/v1alpha/slo/metrics_honeycomb.go
  manifest/v1alpha/slo/metrics_influxdb.go
  manifest/v1alpha/slo/metrics_instana.go
  manifest/v1alpha/slo/metrics_lightstep.go
  manifest/v1alpha/slo/metrics_logic_monitor.go
  manifest/v1alpha/slo/metrics_newrelic.go
  manifest/v1alpha/slo/metrics_opentsdb.go
  manifest/v1alpha/slo/metrics_pingdom.go
  manifest/v1alpha/slo/metrics_prometheus.go
  manifest/v1alpha/slo/metrics_redshift.go
  manifest/v1alpha/slo/metrics_splunk.go
  manifest/v1alpha/slo/metrics_splunk_observability.go
  manifest/v1alpha/slo/metrics_sumo_logic.go
  manifest/v1alpha/slo/metrics_thousand_eyes.go
  manifest/v1alpha/slo/metrics_validation.go
  manifest/v1alpha/slo/time_window.go
  manifest/v1alpha/slo/validation.go
Labels: chore, patch, go

#541 feat: Add e2e tests for Reports, extend reports validation
  manifest/v1alpha/report/validation_system_health_review.go
  manifest/v1alpha/report/validation_test.go
  tests/v1alpha_report_test.go
Labels: enhancement, go, minor

#529 feat: PC-13893 Deprecate usage of objective's value field for Composite SLOs
  internal/manifest/v1alpha/examples/slo_composite.go
  manifest/v1alpha/slo/examples/composite-slo.yaml
  manifest/v1alpha/slo/slo.go
  sdk/test_data/reader/expected/composite_v2_slo.tpl.json
Labels: enhancement, go, minor

#547 fix: PC-14236 SHR thresholds validation for less than 1
  manifest/v1alpha/report/validation_system_health_review.go
  manifest/v1alpha/report/validation_test.go
Labels: bug, patch, go

#528 feat: Add TimeRange to Replay [PC-13699]
  sdk/models/replay.go
  sdk/models/replay_test.go
Labels: enhancement, go, minor, passed-testing

#538 feat: PC-13696 add sdk end to end tests for budget adjustement
  tests/v1alpha_budgetadjustment_test.go
Labels: enhancement, go, minor

#548 fix: PC-13893 Revert changes from #529
  internal/manifest/v1alpha/examples/slo_composite.go
  manifest/v1alpha/slo/examples/composite-slo.yaml
  manifest/v1alpha/slo/slo.go
  sdk/test_data/reader/expected/composite_v2_slo.tpl.json
Labels: bug, patch, go

#551 test: PC-13893 Make E2E tests forward compatible
  tests/v1alpha_slo_test.go
Labels: enhancement, go, minor

#552 fix: validate Splunk Observability release channel
  internal/manifest/v1alpha/examples/direct.go
  manifest/v1alpha/direct/examples/splunk-observability.yaml
  manifest/v1alpha/direct/validation.go
  manifest/v1alpha/direct/validation_test.go
  manifest/v1alpha/release_channel.go
  sdk/config_activity.png
Labels: bug, patch, go

#555 fix: PC-13696 timestamp precision
  tests/v1alpha_budgetadjustment_test.go
Labels: bug, patch, go

#558 feat: extend SLO status replay with source and user [PC-14276]
  manifest/v1alpha/slo/slo.go
  sdk/models/replay.go
Labels: enhancement, go, minor

#557 fix: PC-14338 System Health Review report name should not be longer than 63 chars
  manifest/v1alpha/report/validation_system_health_review.go
  manifest/v1alpha/report/validation_test.go
Labels: bug, patch, go

#562 chore: Add retry to end-to-end workflow run
  .github/workflows/e2e-tests.yml
Labels: chore, patch
