Repository nobl9/nobl9-go, pull requests merged in 2024-11, with the labels that each got.

#577 feat: PC-13791 Add validation to SLO History report's time frame
  internal/manifest/v1alpha/examples/report.go
  manifest/v1alpha/report/example_test.go
  manifest/v1alpha/report/examples.yaml
  manifest/v1alpha/report/validation.go
  manifest/v1alpha/report/validation_slo_history.go
  manifest/v1alpha/report/validation_test.go
  manifest/v1alpha/report/validation_time_frame.go
Labels: enhancement, go, minor

#564 feat: add PromQL to GCM metric spec
  manifest/v1alpha/slo/metrics_gcm.go
  manifest/v1alpha/slo/metrics_gcm_test.go
  manifest/v1alpha/slo/metrics_validation.go
Labels: enhancement, go, minor, passed-testing

#585 feat: Add Replay support to Elasticsearch
  manifest/v1alpha/agent/examples/elasticsearch.yaml
  manifest/v1alpha/data_sources.go
Labels: enhancement, go, minor

#587 fix: CountMetrics validation
  go.mod
  go.sum
  manifest/v1alpha/slo/metrics_instana_test.go
  manifest/v1alpha/slo/metrics_splunk.go
  manifest/v1alpha/slo/metrics_splunk_test.go
  manifest/v1alpha/slo/metrics_validation.go
  manifest/v1alpha/slo/validation.go
  manifest/v1alpha/slo/validation_test.go
Labels: bug, patch, go

#590 feat: Extend list of alert method template variables with `alert_id`
  manifest/v1alpha/alertmethod/notification_template.go
Labels: enhancement, go, minor

#597 fix: Use beta elasticsearch in tests
  internal/manifest/v1alpha/examples/agent.go
  manifest/v1alpha/agent/examples/elasticsearch.yaml
Labels: bug, patch, go

#599 chore: Correct bad/total SLO examples generation
  internal/manifest/v1alpha/examples/slo_variants.go
  manifest/v1alpha/slo/examples/app-dynamics.yaml
  manifest/v1alpha/slo/examples/azure-monitor.yaml
  manifest/v1alpha/slo/examples/azure-prometheus.yaml
  manifest/v1alpha/slo/examples/cloud-watch.yaml
  manifest/v1alpha/slo/examples/honeycomb.yaml
  manifest/v1alpha/slo/examples/logic-monitor.yaml
Labels: chore, patch, go

#596 chore: Remove deprecated Body and Subject from Email alert method
  internal/manifest/v1alpha/examples/alert_method.go
  manifest/v1alpha/alertmethod/alert_method.go
  manifest/v1alpha/alertmethod/examples/email.yaml
Labels: breaking-change, chore, patch, go

#601 chore: Add timeout to e2e-tests.yml
  .github/workflows/e2e-tests.yml
Labels: chore, patch
