Repository nobl9/nobl9-go, pull requests merged in 2024-05, with the labels that each got.

#377 PC-12652 feat: Allow to set any mathematical operator for burnedBudget alerting condition
  manifest/v1alpha/alertpolicy/measurement.go
  manifest/v1alpha/alertpolicy/validation.go
  manifest/v1alpha/alertpolicy/validation_test.go
Labels: go

#384 PC-12164 feat: Additional alert details
  manifest/v1alpha/alert/alert.go
  manifest/v1alpha/alert/example.yaml
Labels: go

#398 Revert "feat: PC-12488 PC-12490 Add LogicMonitor Direct, Agent and Metric Spec (#380)"
  cspell.yaml
  manifest/v1alpha/agent/agent.go
  manifest/v1alpha/agent/validation.go
  manifest/v1alpha/agent/validation_test.go
  manifest/v1alpha/data_sources.go
  manifest/v1alpha/data_sources_enum.go
  manifest/v1alpha/direct/direct.go
  manifest/v1alpha/direct/validation.go
  manifest/v1alpha/direct/validation_test.go
  manifest/v1alpha/slo/metrics.go
  manifest/v1alpha/slo/metrics_logic_monitor.go
  manifest/v1alpha/slo/metrics_logic_monitor_test.go
  manifest/v1alpha/slo/metrics_validation.go
  manifest/v1alpha/slo/validation_test.go
  sdk/config_activity.png
Labels: go

#400 chore: Update pr-title.yml
  .github/workflows/pr-title.yml
Labels: chore, patch

#399 chore: Add code docs extractor
  internal/cmd/docgen/README.md
  internal/cmd/docgen/generator.go
  internal/cmd/docgen/go_doc.go
  internal/cmd/docgen/main.go
  internal/cmd/docgen/map_objects.go
  internal/cmd/docgen/object_doc.go
  internal/cmd/docgen/objects.go
  internal/cmd/docgen/properties.go
  internal/manifest/objects_test.go
  internal/manifest/v1alpha/validation.go
  internal/validation/plan.go
  internal/validation/plan_test.go
  internal/validation/required.go
  internal/validation/rules.go
  internal/validation/rules_for_map.go
  internal/validation/rules_for_slice.go
  internal/validation/test_data/expected_pod_plan.json
  manifest/v1alpha/agent/validation.go
  manifest/v1alpha/agent/validation_test.go
  manifest/v1alpha/alert/alert.go
  manifest/v1alpha/alert/example.yaml
  manifest/v1alpha/alert/validation.go
  manifest/v1alpha/alert/validation_test.go
  manifest/v1alpha/alertmethod/validation.go
  manifest/v1alpha/alertmethod/validation_test.go
  manifest/v1alpha/alertpolicy/validation.go
  manifest/v1alpha/alertpolicy/validation_test.go
  manifest/v1alpha/alertsilence/validation.go
  manifest/v1alpha/alertsilence/validation_test.go
  manifest/v1alpha/annotation/validation.go
  manifest/v1alpha/annotation/validation_test.go
  manifest/v1alpha/budgetadjustment/validation.go
  manifest/v1alpha/budgetadjustment/validation_test.go
  manifest/v1alpha/dataexport/validation.go
  manifest/v1alpha/dataexport/validation_test.go
  manifest/v1alpha/direct/validation.go
  manifest/v1alpha/direct/validation_test.go
  manifest/v1alpha/errors.go
  manifest/v1alpha/labels.go
  manifest/v1alpha/metadata_annotations.go
  manifest/v1alpha/project/project.go
  manifest/v1alpha/project/validation.go
  manifest/v1alpha/project/validation_test.go
  manifest/v1alpha/rolebinding/validation.go
  manifest/v1alpha/rolebinding/validation_test.go
  manifest/v1alpha/service/service.go
  manifest/v1alpha/service/validation.go
  manifest/v1alpha/service/validation_test.go
  manifest/v1alpha/slo/validation.go
  manifest/v1alpha/slo/validation_test.go
  manifest/v1alpha/usergroup/user_group.go
  manifest/v1alpha/usergroup/validation.go
  manifest/v1alpha/usergroup/validation_test.go
Labels: chore, patch, go

#403 fix: PC-12544 Add validation for components list to be required (even if empty)
  manifest/v1alpha/slo/validation.go
  manifest/v1alpha/slo/validation_composite_test.go
Labels: bug, patch, go

#404 test: PC-12019 Add basic tests for `slo.SpecHasCompositeObjectives()`
  manifest/v1alpha/slo/slo_test.go
Labels: enhancement, go, minor

#408 feat: PC-12488 PC-12490 Add LogicMonitor Direct, Agent and Metric Spec
  cspell.yaml
  go.work.sum
  manifest/v1alpha/agent/agent.go
  manifest/v1alpha/agent/validation.go
  manifest/v1alpha/agent/validation_test.go
  manifest/v1alpha/data_sources.go
  manifest/v1alpha/data_sources_enum.go
  manifest/v1alpha/direct/direct.go
  manifest/v1alpha/direct/validation.go
  manifest/v1alpha/direct/validation_test.go
  manifest/v1alpha/slo/metrics.go
  manifest/v1alpha/slo/metrics_logic_monitor.go
  manifest/v1alpha/slo/metrics_logic_monitor_test.go
  manifest/v1alpha/slo/metrics_validation.go
  manifest/v1alpha/slo/validation_test.go
  sdk/config_activity.png
Labels: enhancement, go, minor

#412 chore: Add option to change output format to compacted JSON in docgen
  internal/cmd/docgen/main.go
Labels: chore, patch, go

#418 feat: add GCM Replay support [PC-12560]
  manifest/v1alpha/data_sources.go
Labels: enhancement, go, minor

#430 fix: Correct Logic Monitor validation
  manifest/v1alpha/slo/metrics_logic_monitor.go
  manifest/v1alpha/slo/metrics_logic_monitor_test.go
Labels: bug, patch, go

#434 chore: Ignore commit suffix
  .github/scripts/release-notes.sh
Labels: chore, patch
