Repository nobl9/nobl9-go, pull requests merged in 2024-03, with the labels that each got.

#302 doc: Update DEVELOPMENT.md
  docs/DEVELOPMENT.md
Labels: documentation

#287 feat: PC-11815 add GetBudgetAdjustments endpoint function
  sdk/endpoints/objects/v1/endpoints_v1alpha.go
  sdk/endpoints/objects/v1/request.go
Labels: enhancement, go, minor

#295 feat: add Lightstep URL [PC-12053]
  manifest/v1alpha/agent/agent.go
  manifest/v1alpha/agent/validation.go
  manifest/v1alpha/agent/validation_test.go
  manifest/v1alpha/direct/direct.go
  manifest/v1alpha/direct/validation.go
  manifest/v1alpha/direct/validation_test.go
Labels: enhancement, go, minor

#310 feat: PC-12274 Add updatedAt to SLO Spec
  manifest/v1alpha/slo/slo.go
Labels: enhancement, go, minor

#311 chore: Delete .github/release.yml
  .github/release.yml
Labels: chore, patch

#312 chore: Update Nobl9 logo
  README.md
Labels: chore, patch

#313 feat: PC-12274 PC-12009 Move updatedAt to status, add createdBy to spec
  manifest/v1alpha/slo/slo.go
Labels: enhancement, go, minor

#280 feat: PC-12012 Composite SLO
  cspell.yaml
  manifest/v1alpha/slo/composite.go
  manifest/v1alpha/slo/example_test.go
  manifest/v1alpha/slo/metrics.go
  manifest/v1alpha/slo/metrics_validation.go
  manifest/v1alpha/slo/slo.go
  manifest/v1alpha/slo/validation.go
  manifest/v1alpha/slo/validation_composite_test.go
  manifest/v1alpha/slo/validation_test.go
  manifest/v1alpha/slo/when_delayed.go
  manifest/v1alpha/slo/when_delayed_enum.go
  sdk/reader_test.go
  sdk/test_data/client/simple_module/go.mod
  sdk/test_data/client/simple_module/go.sum
  sdk/test_data/reader/expected/composite_v2_slo.tpl.json
  sdk/test_data/reader/inputs/composite_v2_slo.yaml
Labels: enhancement, breaking-change, go, minor, release-notes

#317 chore: Update README.md logo
  README.md
Labels: chore, patch

#324 fix: Bring back createdBy and remove duplicate updatedAt
  manifest/v1alpha/slo/slo.go
Labels: bug, patch, go

#330 feat: PC-11745 Add Primary to Objective
  manifest/v1alpha/slo/slo.go
  manifest/v1alpha/slo/validation.go
  manifest/v1alpha/slo/validation_test.go
Labels: enhancement, go, minor

#343 feat: add GetUser() to return current user
  sdk/client.go
  sdk/credentials.go
Labels: enhancement, go, minor
