Repository nobl9/nobl9-go, pull requests merged in 2024-04, with the labels that each got.

#350 fix: Use optional JSON number decoding
  manifest/v1alpha/parser/parser.go
Labels: bug, patch, go

#339 fix: reorder objective validation rules to produce more adequate composite objective validation messages [PC-12021]
  internal/validation/rule.go
  internal/validation/rule_test.go
  manifest/v1alpha/slo/metrics_validation.go
  manifest/v1alpha/slo/validation.go
  manifest/v1alpha/slo/validation_composite_test.go
  manifest/v1alpha/slo/validation_test.go
  sdk/test_data/client/simple_module/go.mod
  sdk/test_data/client/simple_module/go.sum
Labels: bug, patch, go

#356 chore: Update Go to 1.22
  go.mod
  sdk/test_data/client/simple_module/go.mod
Labels: chore, patch, go

#345 feat: Add rules for maps in validation
  internal/validation/errors.go
  internal/validation/example_test.go
  internal/validation/rules_for_map.go
  internal/validation/rules_for_map_test.go
  internal/validation/rules_for_slice.go
  internal/validation/rules_for_slice_test.go
  manifest/v1alpha/alertmethod/validation.go
  manifest/v1alpha/alertpolicy/validation.go
  manifest/v1alpha/budgetadjustment/validation.go
  manifest/v1alpha/slo/metrics_azure_monitor.go
  manifest/v1alpha/slo/metrics_cloudwatch.go
  manifest/v1alpha/slo/validation.go
Labels: enhancement, go, minor

#355 feat: Allow for mocking sdk.Client
  Makefile
  cspell.yaml
  docs/mock_example/README.md
  docs/mock_example/command.go
  docs/mock_example/command_test.go
  docs/mock_example/go.mod
  docs/mock_example/go.sum
  docs/mock_example/mocks/client.go
  docs/mock_example/mocks/objects_v1.go
  docs/mock_example/mocks/objects_versions.go
  go.work
  go.work.sum
  scripts/check-generate.sh
  sdk/config_activity.png
  sdk/endpoints/authdata/v1/endpoints.go
  sdk/endpoints/authdata/v1/endpoints_interface.go
  sdk/endpoints/authdata/versions.go
  sdk/endpoints/authdata/versions_interface.go
  sdk/endpoints/objects/v1/endpoints.go
  sdk/endpoints/objects/v1/endpoints_interface.go
  sdk/endpoints/objects/v1/endpoints_v1alpha.go
  sdk/endpoints/objects/versions.go
  sdk/endpoints/objects/versions_interface.go
Labels: enhancement, go, minor

#359 feat: Improve labels validation
  cspell.yaml
  internal/manifest/v1alpha/validation.go
  internal/manifest/v1alphatest/doc.go
  internal/manifest/v1alphatest/labels_validation.go
  internal/testutils/assert.go
  internal/validation/errors.go
  internal/validation/length.go
  internal/validation/rules_for_map.go
  internal/validation/rules_for_map_test.go
  internal/validation/rules_for_slice.go
  internal/validation/rules_for_slice_test.go
  manifest/v1alpha/agent/test_data/expected_error.txt
  manifest/v1alpha/agent/validation_test.go
  manifest/v1alpha/alertmethod/test_data/expected_metadata_error.txt
  manifest/v1alpha/alertmethod/validation_test.go
  manifest/v1alpha/alertpolicy/test_data/expected_error.txt
  manifest/v1alpha/alertpolicy/validation_test.go
  manifest/v1alpha/alertsilence/test_data/expected_error.txt
  manifest/v1alpha/alertsilence/validation_test.go
  manifest/v1alpha/annotation/test_data/expected_error.txt
  manifest/v1alpha/annotation/validation_test.go
  manifest/v1alpha/budgetadjustment/validation_test.go
  manifest/v1alpha/dataexport/test_data/expected_metadata_error.txt
  manifest/v1alpha/dataexport/validation_test.go
  manifest/v1alpha/direct/test_data/expected_error.txt
  manifest/v1alpha/direct/validation_test.go
  manifest/v1alpha/labels.go
  manifest/v1alpha/labels_test.go
  manifest/v1alpha/project/test_data/expected_error.txt
  manifest/v1alpha/project/validation_test.go
  manifest/v1alpha/rolebinding/test_data/expected_error.txt
  manifest/v1alpha/rolebinding/validation_test.go
  manifest/v1alpha/service/test_data/expected_error.txt
  manifest/v1alpha/service/validation_test.go
  manifest/v1alpha/slo/test_data/expected_metadata_error.txt
  manifest/v1alpha/slo/validation_test.go
  manifest/v1alpha/usergroup/test_data/expected_error.txt
  manifest/v1alpha/usergroup/validation_test.go
Labels: enhancement, go, minor

#342 feat: PC-12282 Introduce metadata annotations
  internal/manifest/v1alpha/validation.go
  internal/manifest/v1alphatest/labels_validation.go
  internal/manifest/v1alphatest/metadata_annotations_validation.go
  internal/validation/rules_for_map.go
  internal/validation/rules_for_map_test.go
  manifest/v1alpha/alertpolicy/alert_policy.go
  manifest/v1alpha/alertpolicy/validation.go
  manifest/v1alpha/alertpolicy/validation_test.go
  manifest/v1alpha/metadata_annotations.go
  manifest/v1alpha/project/project.go
  manifest/v1alpha/project/validation.go
  manifest/v1alpha/project/validation_test.go
  manifest/v1alpha/service/service.go
  manifest/v1alpha/service/validation.go
  manifest/v1alpha/service/validation_test.go
  manifest/v1alpha/slo/slo.go
  manifest/v1alpha/slo/validation.go
  manifest/v1alpha/slo/validation_test.go
  sdk/test_data/client/simple_module/go.mod
  sdk/test_data/client/simple_module/go.sum
Labels: enhancement, go, minor

#365 feat: PC-10331 Add annotation category
  manifest/v1alpha/annotation/annotation.go
  manifest/v1alpha/annotation/validation.go
  manifest/v1alpha/annotation/validation_test.go
Labels: enhancement, go, minor

#361 feat: PC-12071: Add support for alerting window to more measurements
  manifest/v1alpha/alertpolicy/validation.go
  manifest/v1alpha/alertpolicy/validation_test.go
Labels: enhancement, go, minor

#369 feat: Stabilize validation API - When usage
  internal/validation/example_test.go
  internal/validation/rules.go
  internal/validation/rules_for_map.go
  internal/validation/rules_for_slice.go
Labels: enhancement, go, minor

#373 chore: Stabilize validation API - remove StopOnError and simplify internal logic
  internal/testutils/assert.go
  internal/validation/cascade_mode.go
  internal/validation/errors.go
  internal/validation/example_test.go
  internal/validation/predicate.go
  internal/validation/rule_test.go
  internal/validation/rules.go
  internal/validation/rules_for_map.go
  internal/validation/rules_for_map_test.go
  internal/validation/rules_for_slice.go
  internal/validation/rules_for_slice_test.go
  internal/validation/rules_test.go
  internal/validation/string.go
  internal/validation/validator_test.go
  manifest/v1alpha/agent/validation.go
  manifest/v1alpha/alertmethod/validation.go
  manifest/v1alpha/alertpolicy/validation.go
  manifest/v1alpha/alertsilence/validation.go
  manifest/v1alpha/budgetadjustment/validation.go
  manifest/v1alpha/direct/validation.go
  manifest/v1alpha/slo/metrics_azure_monitor.go
  manifest/v1alpha/slo/metrics_azure_monitor_test.go
  manifest/v1alpha/slo/metrics_cloudwatch.go
  manifest/v1alpha/slo/metrics_cloudwatch_test.go
  manifest/v1alpha/slo/metrics_elasticsearch.go
  manifest/v1alpha/slo/metrics_graphite.go
  manifest/v1alpha/slo/metrics_influxdb.go
  manifest/v1alpha/slo/metrics_instana.go
  manifest/v1alpha/slo/metrics_newrelic.go
  manifest/v1alpha/slo/metrics_splunk.go
  manifest/v1alpha/slo/metrics_validation.go
  manifest/v1alpha/slo/validation.go
  sdk/models/replay.go
Labels: chore, patch, go

#380 feat: PC-12488 PC-12490 Add LogicMonitor Direct, Agent and Metric Spec
  cspell.yaml
  manifest/v1alpha/agent/agent.go
  manifest/v1alpha/agent/validation.go
  manifest/v1alpha/agent/validation_test.go
  manifest/v1alpha/data_sources.go
  manifest/v1alpha/data_sources_enum.go
  manifest/v1alpha/direct/direct.go
  manifest/v1alpha/direct/validation.go
  manifest/v1alpha/direct/validation_test.go
  manifest/v1alpha/slo/metrics.go
  manifest/v1alpha/slo/metrics_logic_monitor.go
  manifest/v1alpha/slo/metrics_logic_monitor_test.go
  manifest/v1alpha/slo/metrics_validation.go
  manifest/v1alpha/slo/validation_test.go
  sdk/config_activity.png
Labels: enhancement, go, minor
