Repository nobl9/nobl9-go, pull requests merged in 2025-01, with the labels that each got.

#617 chore: Improve sdk.ReadObjects docs [PC-15261]
  sdk/reader.go
  sdk/source.go
Labels: chore, patch, go

#618 chore: Correct Go code docs - fix links
  internal/serdeutil/raw_message.go
  internal/testutils/assert.go
  manifest/doc.go
  manifest/format.go
  manifest/kind.go
  manifest/object.go
  manifest/v1alpha/labels.go
  manifest/v1alpha/parser/parser_test.go
  manifest/version.go
  sdk/client.go
  sdk/config.go
  sdk/config_file.go
  sdk/credentials.go
  sdk/credentials_test.go
  sdk/decode.go
  sdk/endpoints/authdata/v1/endpoints.go
  sdk/http.go
  sdk/jwt.go
  sdk/models/replay.go
  sdk/reader.go
  sdk/source.go
Labels: chore, patch, go

#615 feat: PC-15221 Add EndTime to replay
  manifest/v1alpha/slo/slo.go
  sdk/models/replay.go
Labels: enhancement, go, minor, passed-testing

#593 feat: Support Website metrics in LogicMonitor [PC-14860]
  internal/manifest/v1alpha/examples/slo_variants.go
  manifest/v1alpha/slo/examples/logic-monitor.yaml
  manifest/v1alpha/slo/metrics_logic_monitor.go
  manifest/v1alpha/slo/metrics_logic_monitor_test.go
  manifest/v1alpha/slo/metrics_validation.go
Labels: enhancement, go, minor

#623 fix: PC-9592 Validate opsgenie and slack URLs at submission
  manifest/v1alpha/alertmethod/validation.go
  manifest/v1alpha/alertmethod/validation_opsgenie_test.go
  manifest/v1alpha/alertmethod/validation_slack_test.go
  manifest/v1alpha/alertmethod/validation_test.go
Labels: bug, enhancement, patch, go, minor, passed-testing

#620 feat: Add filtering by service name to GetV1alphaSLOs
  sdk/endpoints/objects/v1/endpoints_v1alpha.go
  sdk/endpoints/objects/v1/request.go
  tests/main_test.go
  tests/v1alpha_slo_test.go
Labels: enhancement, go, minor

#624 feat: Add Web Transaction Time metric to ThousandEyes
  internal/manifest/v1alpha/examples/slo.go
  internal/manifest/v1alpha/examples/slo_variants.go
  manifest/v1alpha/slo/examples/thousand-eyes.yaml
  manifest/v1alpha/slo/metrics_thousand_eyes.go
Labels: enhancement, go, minor, passed-testing

#630 fix: Correct Report timeFrame paths
  manifest/v1alpha/report/validation_slo_history.go
  manifest/v1alpha/report/validation_test.go
Labels: bug, patch, go

#629 feat: Add new Thousandeyes test type - API transaction time
  internal/manifest/v1alpha/examples/slo.go
  internal/manifest/v1alpha/examples/slo_variants.go
  manifest/v1alpha/slo/examples/thousand-eyes.yaml
  manifest/v1alpha/slo/metrics_thousand_eyes.go
Labels: enhancement, go, minor

#632 feat: PC-14241 budget adjustment spec duration should not have precision set to 1 m
  manifest/v1alpha/budgetadjustment/validation.go
  manifest/v1alpha/budgetadjustment/validation_test.go
Labels: enhancement, go, minor, passed-testing

#631 feat: PC-15436 Add annotation's author ID
  manifest/v1alpha/annotation/annotation.go
Labels: enhancement, go, minor
