Repository nobl9/nobl9-go, pull requests merged in 2025-05, with the labels that each got.

#708 fix: Solve segmentation violation errors for empty APIVersion [PC-16865]
  go.mod
  go.sum
  sdk/encode_test.go
Labels: bug, patch, go

#711 fix: Remove replace directive for go-yaml and set it directly
  go.mod
Labels: bug, patch, go

#703 feat: Add send resolution to Service Now
  manifest/v1alpha/alertmethod/alert_method.go
  manifest/v1alpha/alertmethod/validation.go
Labels: enhancement, go, minor

#709 feat: Allow to configure Email alert method as plain text
  internal/manifest/v1alpha/examples/alert_method.go
  manifest/v1alpha/alertmethod/alert_method.go
  manifest/v1alpha/alertmethod/examples/email.yaml
  manifest/v1alpha/alertmethod/validation_email_test.go
Labels: enhancement, go, minor

#726 feat: Add users API
  sdk/client.go
  sdk/endpoints/users/doc.go
  sdk/endpoints/users/v2/doc.go
  sdk/endpoints/users/v2/endpoints.go
  sdk/endpoints/users/v2/endpoints_interface.go
  sdk/endpoints/users/v2/request.go
  sdk/endpoints/users/v2/response.go
  sdk/endpoints/users/versions.go
  sdk/endpoints/users/versions_interface.go
  tests/helpers_test.go
  tests/slostatusapi_test.go
  tests/users_test.go
Labels: enhancement, go, minor

#718 feat: PC-16904 Add cancellation field to SLO's status and Replay's status
  manifest/v1alpha/slo/slo.go
  sdk/models/replay.go
Labels: enhancement, go, minor

#722 feat: PC-16916 Add canceledBy field to replay status
  manifest/v1alpha/slo/slo.go
  sdk/models/replay.go
Labels: enhancement, go, minor

#730 chore: fix v1alpha.Agent and v1alpha.Direct e2e tests [PC-16874]
  internal/manifest/v1alpha/examples/agent.go
  internal/manifest/v1alpha/examples/direct.go
  manifest/v1alpha/agent/examples/thousand-eyes.yaml
  manifest/v1alpha/direct/examples/thousand-eyes.yaml
  tests/v1alpha_agent_test.go
Labels: chore, patch, go

#729 feat: Improve FileConfig handling
  sdk/client_test.go
  sdk/config.go
  sdk/config_test.go
Labels: enhancement, breaking-change, go, minor

#734 fix: Correct API errors handling
  sdk/http_errors.go
  sdk/http_errors_test.go
Labels: bug, patch, go
