Repository nobl9/nobl9-go, pull requests merged in 2025-07, with the labels that each got.

#745 feat: Support for labels for v1alpha.Annotation
  manifest/v1alpha/annotation/annotation.go
  manifest/v1alpha/annotation/example_test.go
  manifest/v1alpha/annotation/examples.yaml
  manifest/v1alpha/annotation/validation.go
  manifest/v1alpha/annotation/validation_test.go
  manifest/v1alpha/examples/annotation.go
  tests/v1alpha_annotation_test.go
Labels: enhancement, go, minor

#769 feat: service review cycle
  manifest/v1alpha/service/example_test.go
  manifest/v1alpha/service/service.go
  manifest/v1alpha/service/validation.go
  manifest/v1alpha/service/validation_test.go
Labels: enhancement, go, minor, passed-testing

#768 chore: add post-upgrade tasks to run `make generate` in Renovate
  .github/renovate.json5
Labels: chore, patch
