Repository nobl9/nobl9-go, pull requests merged in 2025-04, with the labels that each got.

#673 feat: Upgrade Go to 1.24
  .golangci.yml
  Makefile
  go.mod
  go.sum
  go.work
  internal/cmd/docgen/go_doc.go
  internal/cmd/docgen/main.go
  internal/manifest/v1alphatest/labels_validation.go
  internal/manifest/v1alphatest/metadata_annotations_validation.go
  manifest/v1alpha/alert/example_test.go
  manifest/v1alpha/dataexport/data_export.go
  manifest/v1alpha/parser/parser.go
  manifest/v1alpha/parser/parser_test.go
  sdk/decode.go
  sdk/decode_test.go
  sdk/encode.go
Labels: enhancement, go, minor

#674 fix: PC-16593 Wrongly calculated calendar-aligned time windows starting at 29th-31st day of the month
  manifest/v1alpha/twindow/twindow.go
  manifest/v1alpha/twindow/twindow_test.go
Labels: bug, patch, go

#662 chore: Allow the use of milliseconds in Elastic queries to support OpenTelemetry span querying
  manifest/v1alpha/slo/metrics_elasticsearch.go
  manifest/v1alpha/slo/metrics_elasticsearch_test.go
  manifest/v1alpha/slo/validation_test.go
Labels: chore, patch, go

#679 chore: Add omitempty tag to SLO alertPolicies
  manifest/v1alpha/slo/slo.go
  sdk/test_data/reader/expected/composite_v2_slo.tpl.json
  sdk/test_data/reader/expected/slo.tpl.json
Labels: breaking-change, chore, patch, go

#683 feat: Add annotations to Direct
  internal/manifest/v1alpha/examples/direct.go
  manifest/v1alpha/direct/direct.go
  manifest/v1alpha/direct/examples/app-dynamics.yaml
  manifest/v1alpha/direct/examples/azure-monitor.yaml
  manifest/v1alpha/direct/examples/azure-prometheus.yaml
  manifest/v1alpha/direct/examples/big-query.yaml
  manifest/v1alpha/direct/examples/cloud-watch.yaml
  manifest/v1alpha/direct/examples/datadog.yaml
  manifest/v1alpha/direct/examples/dynatrace.yaml
  manifest/v1alpha/direct/examples/google-cloud-monitoring.yaml
  manifest/v1alpha/direct/examples/honeycomb.yaml
  manifest/v1alpha/direct/examples/influx-d-b.yaml
  manifest/v1alpha/direct/examples/instana.yaml
  manifest/v1alpha/direct/examples/lightstep.yaml
  manifest/v1alpha/direct/examples/logic-monitor.yaml
  manifest/v1alpha/direct/examples/new-relic.yaml
  manifest/v1alpha/direct/examples/pingdom.yaml
  manifest/v1alpha/direct/examples/redshift.yaml
  manifest/v1alpha/direct/examples/splunk-observability.yaml
  manifest/v1alpha/direct/examples/splunk.yaml
  manifest/v1alpha/direct/examples/sumo-logic.yaml
  manifest/v1alpha/direct/examples/thousand-eyes.yaml
  manifest/v1alpha/direct/validation.go
  manifest/v1alpha/direct/validation_test.go
Labels: enhancement, go, minor

#684 feat: Add annotations to Agent
  internal/manifest/v1alpha/examples/agent.go
  manifest/v1alpha/agent/agent.go
  manifest/v1alpha/agent/examples/amazon-prometheus.yaml
  manifest/v1alpha/agent/examples/app-dynamics.yaml
  manifest/v1alpha/agent/examples/azure-monitor.yaml
  manifest/v1alpha/agent/examples/azure-prometheus.yaml
  manifest/v1alpha/agent/examples/big-query.yaml
  manifest/v1alpha/agent/examples/cloud-watch.yaml
  manifest/v1alpha/agent/examples/coralogix.yaml
  manifest/v1alpha/agent/examples/datadog.yaml
  manifest/v1alpha/agent/examples/dynatrace.yaml
  manifest/v1alpha/agent/examples/elasticsearch.yaml
  manifest/v1alpha/agent/examples/generic.yaml
  manifest/v1alpha/agent/examples/google-cloud-monitoring.yaml
  manifest/v1alpha/agent/examples/grafana-loki.yaml
  manifest/v1alpha/agent/examples/graphite.yaml
  manifest/v1alpha/agent/examples/honeycomb.yaml
  manifest/v1alpha/agent/examples/influx-d-b.yaml
  manifest/v1alpha/agent/examples/instana.yaml
  manifest/v1alpha/agent/examples/lightstep.yaml
  manifest/v1alpha/agent/examples/logic-monitor.yaml
  manifest/v1alpha/agent/examples/new-relic.yaml
  manifest/v1alpha/agent/examples/open-t-s-d-b.yaml
  manifest/v1alpha/agent/examples/pingdom.yaml
  manifest/v1alpha/agent/examples/prometheus.yaml
  manifest/v1alpha/agent/examples/redshift.yaml
  manifest/v1alpha/agent/examples/splunk-observability.yaml
  manifest/v1alpha/agent/examples/splunk.yaml
  manifest/v1alpha/agent/examples/sumo-logic.yaml
  manifest/v1alpha/agent/examples/thousand-eyes.yaml
  manifest/v1alpha/agent/validation.go
  manifest/v1alpha/agent/validation_test.go
Labels: enhancement, go, minor

#670 feat: Add new custom fields to webhook (for no data anomalies)
  internal/manifest/v1alpha/examples/alert_method.go
  manifest/v1alpha/alertmethod/examples/webhook.yaml
  manifest/v1alpha/alertmethod/notification_template.go
  manifest/v1alpha/alertmethod/validation_webhook_test.go
Labels: enhancement, go, minor

#689 chore: Correct end-to-end tests for v1alpha SLO
  tests/v1alpha_slo_test.go
Labels: chore, patch, go

#690 chore: Update opsgenie example
  internal/manifest/v1alpha/examples/alert_method.go
  manifest/v1alpha/alertmethod/examples/opsgenie.yaml
Labels: chore, patch, go

#696 chore: Bump govy to 0.16.0
  go.mod
  go.sum
  internal/cmd/docgen/objects.go
  manifest/v1alpha/slo/metrics_cloudwatch.go
  manifest/v1alpha/slo/metrics_validation.go
Labels: chore, patch, go

#697 feat: Allow reading raw definitions from ObjectSource
  sdk/decode.go
  sdk/reader.go
  sdk/reader_test.go
Labels: enhancement, go, minor

#685 feat: Allow to set `alertAfter` for SLO no data alerts
  internal/manifest/v1alpha/examples/slo_variants.go
  manifest/v1alpha/slo/examples/amazon-prometheus.yaml
  manifest/v1alpha/slo/examples/app-dynamics.yaml
  manifest/v1alpha/slo/examples/azure-monitor.yaml
  manifest/v1alpha/slo/examples/azure-prometheus.yaml
  manifest/v1alpha/slo/examples/big-query.yaml
  manifest/v1alpha/slo/examples/cloud-watch.yaml
  manifest/v1alpha/slo/examples/coralogix.yaml
  manifest/v1alpha/slo/examples/datadog.yaml
  manifest/v1alpha/slo/examples/dynatrace.yaml
  manifest/v1alpha/slo/examples/elasticsearch.yaml
  manifest/v1alpha/slo/examples/generic.yaml
  manifest/v1alpha/slo/examples/google-cloud-monitoring.yaml
  manifest/v1alpha/slo/examples/grafana-loki.yaml
  manifest/v1alpha/slo/examples/graphite.yaml
  manifest/v1alpha/slo/examples/honeycomb.yaml
  manifest/v1alpha/slo/examples/influx-d-b.yaml
  manifest/v1alpha/slo/examples/instana.yaml
  manifest/v1alpha/slo/examples/lightstep.yaml
  manifest/v1alpha/slo/examples/logic-monitor.yaml
  manifest/v1alpha/slo/examples/new-relic.yaml
  manifest/v1alpha/slo/examples/open-t-s-d-b.yaml
  manifest/v1alpha/slo/examples/pingdom.yaml
  manifest/v1alpha/slo/examples/prometheus.yaml
  manifest/v1alpha/slo/examples/redshift.yaml
  manifest/v1alpha/slo/examples/splunk-observability.yaml
  manifest/v1alpha/slo/examples/splunk.yaml
  manifest/v1alpha/slo/examples/sumo-logic.yaml
  manifest/v1alpha/slo/examples/thousand-eyes.yaml
  manifest/v1alpha/slo/slo.go
  manifest/v1alpha/slo/validation.go
  manifest/v1alpha/slo/validation_test.go
  tests/v1alpha_slo_test.go
Labels: enhancement, breaking-change, go, minor
