Repository nobl9/nobl9-go, pull requests merged in 2025-02, with the labels that each got.

#642 chore: Fix Annotations e2e tests
  tests/v1alpha_annotation_test.go
Labels: chore, patch, go

#633 feat: Update Honeycomb config to forbid raw metrics; support good total single query only [PC-15396]
  .gitignore
  internal/manifest/v1alpha/examples/slo.go
  internal/manifest/v1alpha/examples/slo_variants.go
  internal/manifest/v1alpha/slo/slo.go
  manifest/v1alpha/slo/examples/honeycomb.yaml
  manifest/v1alpha/slo/metrics_honeycomb.go
  manifest/v1alpha/slo/metrics_honeycomb_test.go
  manifest/v1alpha/slo/metrics_validation.go
  manifest/v1alpha/slo/validation_test.go
Labels: enhancement, go, minor, passed-testing

#655 fix: Correct labels usage in Report object
  internal/manifest/v1alpha/examples/report.go
  internal/manifest/v1alpha/examples/slo_composite.go
  manifest/v1alpha/report/report.go
  manifest/v1alpha/report/system_health_review.go
  manifest/v1alpha/report/validation_system_health_review.go
  manifest/v1alpha/report/validation_test.go
  manifest/v1alpha/report/validation_time_frame.go
  tests/v1alpha_report_test.go
  tests/v1alpha_slo_test.go
Labels: bug, breaking-change, patch, go
